// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSoG4bLV81Y-ONZHpbNiXBLnIsA599l0',
    appId: '1:739131917133:android:4b0bee9cc75a441bbced04',
    messagingSenderId: '739131917133',
    projectId: 'fineeeeeshhh',
    databaseURL: 'https://fineeeeeshhh-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fineeeeeshhh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2EU2MLLTLsA6Bd2ZuhktSzqfx9UgCLes',
    appId: '1:739131917133:ios:45821c4746e5bbe5bced04',
    messagingSenderId: '739131917133',
    projectId: 'fineeeeeshhh',
    databaseURL: 'https://fineeeeeshhh-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fineeeeeshhh.firebasestorage.app',
    iosBundleId: 'com.example.resturantapp',
  );

}